# Generated by Django 5.0 on 2024-03-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0016_alter_address_country_alter_address_zip_code_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='img',
            new_name='image',
        ),
    ]
