# Generated by Django 5.0 on 2024-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0020_alter_product_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.CharField(blank=True, choices=[('0 - 500', '0 - 500'), ('500 - 3000', '500 - 3000'), ('3000 - 10000', '3000 - 10000'), ('10000 - 40000', '10000 - 40000'), ('40000 - 60000', '40000 - 60000')], max_length=50, null=True),
        ),
    ]
