# Generated by Django 5.0 on 2024-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0021_product_star_alter_product_price1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(),
        ),
    ]
