# Generated by Django 5.0 on 2024-04-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0028_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
