# Generated by Django 5.0 on 2024-04-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0029_remove_profile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
