# Generated by Django 5.0 on 2024-04-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0030_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='https://bootdey.com/img/Content/avatar/avatar7.png', upload_to=''),
        ),
    ]
