# Generated by Django 5.0 on 2024-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0032_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
