# Generated by Django 5.0 on 2024-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0035_alter_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size1',
        ),
        migrations.AddField(
            model_name='product',
            name='size1',
            field=models.ManyToManyField(blank=True, null=True, to='shooper_app.size'),
        ),
    ]
