# Generated by Django 5.0 on 2024-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0036_remove_product_size1_product_size1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='shooper_app.color'),
        ),
    ]
