# Generated by Django 5.0.6 on 2024-07-05 10:33

import shooper_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0037_remove_product_color_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img', validators=[shooper_app.models.delete_file_in_folder])),
            ],
        ),
    ]
