# Generated by Django 5.0.6 on 2024-07-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0040_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_track',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Reaches at Ahmedabad', 'Reaches at Ahmedabad'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Pakistan', 'Pakistan'), ('America', 'America'), ('Afghanistan', 'Afghanistan'), ('London', 'London'), ('Canada', 'Canada')], max_length=50, null=True),
        ),
    ]
