# Generated by Django 5.0.6 on 2024-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooper_app', '0042_alter_order_order_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_track',
            field=models.CharField(blank=True, choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('Reaches at Ahmedabad', 'Reaches at Ahmedabad'), ('Delivered', 'Delivered')], default='Order Placed', max_length=50, null=True),
        ),
    ]
